name: Android Build

on:
  workflow_dispatch: # run manually

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Setup Java for Android build
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"

      # 3️⃣ Setup Node.js
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # 4️⃣ Install dependencies (ignore peer deps for React 19 conflict)
      - name: Install Dependencies
        run: npm install --legacy-peer-deps

      # 5️⃣ Build & export static site for Capacitor
      - name: Build Web App
        run: |
          echo '--- Building Next.js static export ---'
          npm run build
          npx next export

      # 6️⃣ Install Capacitor + Android
      - name: Install Capacitor
        run: |
          echo '--- Installing Capacitor ---'
          npm install @capacitor/core @capacitor/cli @capacitor/android
          npx cap init "MyV0App" "com.myv0.app" --web-dir=out
          npx cap add android
          npx cap sync android

      # 7️⃣ Ensure gradlew executable
      - name: Ensure gradlew permission
        run: chmod +x android/gradlew

      # 8️⃣ Build the Android APK
      - name: Build APK
        run: |
          cd android
          ./gradlew assembleDebug

      # 9️⃣ Upload the generated APK as artifact
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: MyV0App-debug
          path: android/app/build/outputs/apk/debug/app-debug.apk
